import express from 'express';
import { config } from './config.js';
import { getBlock, getMarket } from './chain.js';
import {
  getCurrentPerformance,
  getFlows,
  getHistory,
  getPerformanceAt,
  resolveBlock,
  serialise,
} from './position.js';
import {
  costOfFundsAt,
  costSummaryAt,
  getCostOfFundsBreakdown,
  getCostSeries,
} from './cost.js';
import { amount } from './format.js';

const app = express();
app.disable('x-powered-by');
app.set('json spaces', 2);

// BigInt values never reach res.json — everything is serialised to strings first —
// but guard anyway so an oversight surfaces as a string instead of a 500.
BigInt.prototype.toJSON = function () {
  return this.toString();
};

const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res)).catch(next);

const bad = (message) => Object.assign(new Error(message), { status: 400 });

/** Parse an optional integer query param, rejecting anything non-numeric. */
function intParam(query, name) {
  const raw = query[name];
  if (raw == null || raw === '') return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n) || !Number.isInteger(n) || n < 0) {
    throw bad(`\`${name}\` must be a non-negative integer, got "${raw}".`);
  }
  return n;
}

/** Parse an optional ISO date query param into unix seconds. */
function dateParam(query, name) {
  const raw = query[name];
  if (raw == null || raw === '') return undefined;
  const ms = new Date(raw).getTime();
  if (Number.isNaN(ms)) throw bad(`\`${name}\` is not a valid date, got "${raw}".`);
  return Math.floor(ms / 1000);
}

app.get('/', (_req, res) => {
  res.json({
    service: 'osero-spusds-monitoring',
    description:
      "Yield generated by Osero's ALM Proxy allocation into SparkLend spUSDS, from inception to now.",
    holder: config.holder,
    aToken: config.aToken,
    endpoints: {
      'GET /health': 'Liveness probe.',
      'GET /performance':
        'Current snapshot: principal, balance, yield since inception, cost of funds, net profit.',
      'GET /performance/at?date=|timestamp=|block=': 'The same snapshot at a past point in time.',
      'GET /performance/history?interval=hour|day|week&from=&to=':
        'Cumulative yield, cost of funds and net profit from inception to now.',
      'GET /cost-of-funds': 'Day-by-day cost-of-funds breakdown with every input to the charge.',
      'GET /flows': 'Every principal deposit/withdrawal detected on the position.',
    },
  });
});

app.get('/health', wrap(async (_req, res) => {
  const block = await getBlock();
  res.json({ status: 'ok', chainId: config.chainId, latestBlock: Number(block.number) });
}));

app.get('/performance', wrap(async (_req, res) => {
  const perf = await getCurrentPerformance();
  const cost = await costSummaryAt(perf.asOf.timestamp, BigInt(perf.yield.sinceInception.raw));
  res.json({ ...perf, ...cost });
}));

app.get('/performance/at', wrap(async (req, res) => {
  const { blockNumber, timestamp } = await resolveBlock({
    block: intParam(req.query, 'block'),
    timestamp: intParam(req.query, 'timestamp') ?? dateParam(req.query, 'date'),
  });
  const perf = serialise(await getPerformanceAt(blockNumber, timestamp));
  const cost = await costSummaryAt(timestamp, BigInt(perf.yield.sinceInception.raw));
  res.json({ ...perf, ...cost });
}));

app.get('/performance/history', wrap(async (req, res) => {
  const limit = intParam(req.query, 'limit') ?? 400;
  if (limit < 2 || limit > 2000) throw bad('`limit` must be between 2 and 2000.');
  const history = await getHistory({
    interval: req.query.interval || 'day',
    from: intParam(req.query, 'from') ?? dateParam(req.query, 'fromDate'),
    to: intParam(req.query, 'to') ?? dateParam(req.query, 'toDate'),
    limit,
  });

  // Overlay cost of funds and net profit onto each point. The daily cost
  // series is built once and interpolated, so this costs no extra RPC beyond
  // what the series itself needs.
  const { rows, decimals } = await getCostSeries();
  let prevCof = null;
  for (const p of history.points) {
    const cof = costOfFundsAt(rows, p.timestamp);
    p.cumulativeCostOfFunds = amount(cof, decimals);
    p.periodCostOfFunds = amount(prevCof === null ? cof : cof - prevCof, decimals);
    p.cumulativeNet = amount(BigInt(p.cumulativeYield.raw) - cof, decimals);
    p.periodNet = amount(
      BigInt(p.periodYield.raw) - BigInt(p.periodCostOfFunds.raw),
      decimals
    );
    prevCof = cof;
  }
  res.json(history);
}));

app.get('/cost-of-funds', wrap(async (_req, res) => {
  res.json(await getCostOfFundsBreakdown());
}));

app.get('/flows', wrap(async (_req, res) => {
  const [flows, market] = await Promise.all([getFlows(), getMarket()]);
  const { formatUnits } = await import('viem');
  res.json({
    holder: config.holder,
    asset: market.underlying,
    count: flows.length,
    flows: flows.map((f) => ({
      blockNumber: Number(f.blockNumber),
      timestamp: f.timestamp,
      date: new Date(f.timestamp * 1000).toISOString(),
      direction: f.direction,
      amount: formatUnits(f.amount > 0n ? f.amount : -f.amount, market.underlying.decimals),
      transactions: f.transactions,
    })),
  });
}));

app.use((_req, res) => res.status(404).json({ error: 'Not found' }));

app.use((err, _req, res, _next) => {
  const status = err.status || 502;
  if (status >= 500) console.error(err);
  res.status(status).json({ error: err.message || 'Internal error' });
});

app.listen(config.port, '0.0.0.0', () => {
  console.log(`osero-spusds-monitoring listening on :${config.port}`);
  console.log(`  holder ${config.holder}  aToken ${config.aToken}`);
});
